function(turn_on_sanitizers)
    if(NOT CMAKE_BUILD_TYPE STREQUAL Debug)
        return()
    endif()

    if(${CMAKE_CXX_COMPILER_ID} MATCHES "MSVC")
        add_compile_options("/fsanitize=address")
    elseif(${CMAKE_CXX_COMPILER_ID} MATCHES "Clang" OR ${CMAKE_CXX_COMPILER_ID} MATCHES "GNU")
        add_compile_options("-fno-omit-frame-pointer" "-fsanitize=address" "-fsanitize=undefined")
        add_link_options("-fno-omit-frame-pointer" "-fsanitize=address" "-fsanitize=undefined")
    else()
        message(SEND_ERROR "sanitizer is Not supported Compiler")
    endif()
endfunction(turn_on_sanitizers)
